<a href="https://colab.research.google.com/github/santhoshmc/machine-learning/blob/main/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basics

##Basics

In [8]:
import numpy as np

In [9]:
np.__version__

'1.21.6'

In [3]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
a = np.arange(15).reshape(3,5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
a = np.arange(16).reshape(3,5)
print(a)

ValueError: ignored

In [7]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.dtype

dtype('int64')

In [13]:
a.dtype.name

'int64'

In [14]:
a.size

15

In [15]:
type(a)

numpy.ndarray

In [17]:
b = np.array([1,2,3])
b

array([1, 2, 3])

##Array creation

In [18]:
a = np.array([3,5,8])
a

array([3, 5, 8])

In [19]:
a.dtype

dtype('int64')

In [20]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [21]:
b = np.array([1.2, 3.5, 5])
b.dtype

dtype('float64')

In [22]:
c = np.array(['cat','dog','rat'])
c.dtype

dtype('<U3')

In [23]:
d = np.array([1,5.6,'bird'])
d.dtype

dtype('<U32')

In [24]:
d

array(['1', '5.6', 'bird'], dtype='<U32')

In [26]:
a = (6,7,8)
b =[4,7]
e = np.array(a)
print(e)

[6 7 8]


In [27]:
e

array([6, 7, 8])

In [28]:
f = np.array(b)
f

array([4, 7])

In [29]:
a = np.array(7,56,43,20)

TypeError: ignored

In [30]:
a = np.array([7,56,43,20 ])
print(a)

[ 7 56 43 20]
